M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2025-12-05T16:25:23-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-05T16:25:23-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X107.73Y-88.67
X171.65Y-71.865
X171.65Y-96.065
M30
