M48
; DRILL file {KiCad 9.0.2} date 2025-11-18T20:52:20-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-18T20:52:20-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.100
%
G90
G05
T1
X112.76Y-74.18
X118.54Y-74.18
T2
X153.275Y-97.235
X156.275Y-97.235
T3
X107.65Y-71.665
X171.65Y-71.865
X171.65Y-96.065
M30
